### ISSUE TITLE
Do you have any ideas for latency predictor model? How to build the model for own target hardware?

### ISSUE THREAD

**Issue by Jon-drugstore** [twice154/ofa-pytorch#1]

**Comment by twice154** [comment]
First of all, this repository didn't consider latency when looking for the architecture.

However, you can add latency constraint of Once-for-All implementation.

As this code is heavily written above OFA, please check OFA tutorial.
- https://colab.research.google.com/github/mit-han-lab/once-for-all/blob/master/tutorial/ofa.ipynb
